FROM maven:3.9.6-eclipse-temurin-11 AS build
WORKDIR /workspace
COPY . .
RUN mvn -q -DskipTests -pl storefront-service -am package

FROM eclipse-temurin:11-jre
WORKDIR /app
COPY --from=build /workspace/storefront-service/target/storefront-service-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
