spring.datasource.url=${ORDER_DB_URL:jdbc:mysql://localhost:3306/sree_nithya_orders}
spring.datasource.username=${ORDER_DB_USERNAME:aurora}
spring.datasource.password=${ORDER_DB_PASSWORD:aurora}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.h2.console.enabled=false
