server.port=8081
spring.application.name=product-service
spring.datasource.url=jdbc:h2:file:./data/product-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
internal.api.token=${INTERNAL_API_TOKEN:demo-internal-token}
spring.datasource.url=jdbc:h2:file:./data/order-db;AUTO_SERVER=TRUE
