spring.application.name=product-service

# Render port support
server.port=${PORT:8081}

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/product-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Internal API Token
internal.api.token=${INTERNAL_API_TOKEN:demo-internal-token}
