spring.datasource.url=${STOREFRONT_DB_URL:jdbc:mysql://localhost:3306/sree_nithya_storefront}
spring.datasource.username=${STOREFRONT_DB_USERNAME:aurora}
spring.datasource.password=${STOREFRONT_DB_PASSWORD:aurora}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
